[Le jeu] TODO

# Cahier des charges

## Introduction

### Histoire

Le joueur commence la partie en se réveillant dans un bureau.
Il ne sait rien d'autre : son identité, sa localisation, sa raison d'être ici lui sont inconnues.
Le joueur va ainsi devoir explorer les lieux pour espérer trouver des réponses à ses questions.

Son exploration est rythmée par des endormissements fréquents, suivis par des réveils.
Cet évènement le fera reset dans la salle de départ, à chaque palier important de progression.

Au fur et à mesure, le joueur apprend qu'il se situe dans l'open space (vide) de [insérer nom entreprise], une entreprise connue spécialisée dans le développement d'Intelligence Artificielle.
Il découvre que [nom entreprise] travaille actuellement sur un gros projet très médiatisé : le développement d'une Intelligence Artificielle "ultime", [nom du projet], qui promet d'imiter le comportement humain à la perfection.
Son exploration va l'emmener à découvrir tous les non-dits autour de ce projet, les rivalités, les arrangements secrets, etc ... qui vont pimenter un peu notre histoire.
Ces éléments devront fournir des pistes de reflexion au joueur, de manière à ce qu'il puisse s'imaginer un scénario crédible concernant son identité et sa raison d'être ici.
Cependant, le récit est parsemé d'incohérences qui doivent laisser au joueur un goût un peu amer vis à vis de ses conclusions, des éléments qui lui laissent penser qu'il n'a pas encore bien tout compris, comme si il lui manquait une pièce du puzzle.
Et en effet, c'est en pénétrant dans la salle des archives et en trouvant un dossier à son nom que le joueur va se rendre compte quil est en fait l'IA "ultime" autour de laquelle toute l'histoire est centrée.

Pour l'instant, le jeu se finira sur un nouveau réveil du joueur, cette fois-ci entourée de l'équipe chargée de son développement, tout sourire.

### Carte

TODO

### Gestion de l'inventaire TODO

Tout le long du jeu, le protagoniste est équipé d'un inventaire ouvrable contenant un ensemble d'objet.
Lorsqu'un objet est pris, il est ajouté dans l'inventaire à capacité infinie.

Un objet peut être équipé (tenu dans la main du protagoniste). Un seul objet à la fois peut être équipé.
Il est nécessaire d'équiper l'objet que l'on veut utiliser.
C'est le seul objet pouvant être utilisé avec un autre objet ou un élément de la salle actuelle.

### Déplacement

Le déplacement s'effectue de salle en salle. 
Une salle peut être accédée via l'une des portes proposées sur l'interface, si elle n'est pas verrouillée.

### Investigation

Lorsqu'il rentre dans une salle, le protagoniste prend connaissance des différents éléments qui s'y trouvent si la lumière le permet.
Différents éléments de chaque salle peuvent être examinés.
Certains objets peuvent également être récupérés et placés dans l'inventaire à condition de ne pas avoir la main paralysée.
Un objet pourra être utilisé ultérieurement pour débloquer de nouveaux objets ou de nouvelles salles. 

### Rencontre PNJ

Le joueur est l'unique entité "vivante" présente dans l'espace de jeu.
Ainsi, les seuls PNJ qu'il recontre sont les ordinateurs de travail des employés de l'entreprise, laissés sur place.
Ces ordinateurs sont tous habités par [nom IA vocale], une intelligence artificelle d'aide au développement créée par [nom de l'entreprise].
[nom IA vocale] est particulièrement bavarde pour un logiciel, et possède l'avantage de ne pas pouvoir faire la distinction entre un humain et une machine.

Le joueur peut interargir avec certains des ordinateurs qui lui sont décris lorsqu'il entre dans une pièce.
*utiliser ordinateur[n° ordi]* --> Le joueur se place en face de l'ordinateur et l'allume. [nom IA vocale] initie la discussion. Une liste de n réponses est proposée au joueur.
*répondre [n° réponse]" --> Le joueur rentre la réponse numéro [n° réponse] dans l'ordinateur. [nom IA vocale] lui répond en conséquence, en lui proposant générallement une nouvelle liste de m réponses.
*quitter* --> Interrompt la discussion entre le joueur et [nom IA vocale]. Peut être utilisée à tout moment. Le joueur se retrouve alors dans le même état que lorsqu'il rentre dans une pièce.
Si le joueur n'a aucune proposition de réponse, il ne peut que utiliser la commande *quitter*.

### Déroulement d'un épisode

Le protagoniste se réveille dans le bureau initial à chaque début d'épisode.
Un épisode est défini par une liste d'objets à récupérer dans les pièces accessibles.
Le protagoniste passe à l'épisode suivant une fois que tous les objets de la liste sont récupérés.

#### Episode 1

Le joueur se réveille dans le bureau initial.

BUREAU INITIAL : Communique avec PC. IA vocale nous introduit le jeu. On veut ouvrir la session pour obtenir des infos sur nous, mais il nous manque le mdp.
On veut sortir explorer mais bureau fermé à clef.
La clef se trouve qq part de le bureau (tiroir/armoir/poche de blouson).
Une fois qu'on l'a, on peut sortir.
Sur l'écran du pc est affiché un username particulier (qui ne donne pas d'info sur qui on est), mais on n'a pas le mot de passe.
Une fois que l'on rentre le mdp, on ouvre la session. De là, on peut accéder à un échange de mail entre le propriétaire de l'ordinateur (que je crois être moi) et un collègue.
Il y est question de surmenage et de menace de grève/révolte si jamais le rythme de travail reste aussi insoutenable.
On s'endort et let's go on pour le prochain épisode.

OPEN SPACE : Pleins de pc qui donnent tous des infos sur le lore : l'identité de l'entreprise et le projet IA ultime (sous sa version grand publique, "positive").
On peut se faire un café, ranger des dossiers, et d'autres actions random.
Un ordinateur nous réclame d'ailleurs de quoi se réveiller pour pouvoir nous parler, (en même temps on est en pleins milieu de la nuit). 
Quand on lui donne un café, nous apprend qu'il faut ouvrir la porte d'une certaine manière pour pouvoir accéder à la salle d'entrée.

SALLE D'ATTENTE : Salle fermée. Action de l'ouvrir "spécialement" se débloque après avoir donné son café à l'ordi.
A l'intérieur se trouve pleins de décos relatives à la boîte, dont une sur laquelle est affichée "Sudo est ton ami".
Doit pas être trop subtile car doit donner l'idée au joueur d'utiliser "sudo" pour déverrouiller le pc dans bureau initial.

### Salles

#### Bureau Initial

Éléments présents : 1 interrupteur, 1 porte, 1 ordinateurs, 1 bureau, 1 fenêtre, 1 étagère, 2 chaises, 1 poubelle

Objets présents : 

#### Open-Space

Éléments présents : 4 interrupteurs, 4 portes (Nord, Sud, Nord Est, Sud Est), 6 ordinateurs, 6 bureaux, 2 fenêtres, 6 chaises, 4 poubelles, 2 tiroirs/bureau, 1 imprimante.

Objets présents : 

#### Archives

Éléments présents : 2 interrupteurs, 2 étagères, 4 cartons, 2 portes (Nord, Sud)

Objets présents : 

#### Salle de réunion

Éléments présents : 2 interrupteurs (celui de la porte Ouest HS), 2 portes (Est, Ouest), 1 table, 10 chaises, 1 étagère, 1 fenêtre.

Objets présents :

#### Salle d'attente

Éléments présents : 2 portes (Est, Ouest), 2 interrupteurs, 8 chaises, 1 table.

Objets présents : 

#### Couloir

Éléments présents : 4 portes (Nord Est, Nord Ouest, Sud Est, Sud Ouest), 4 interrupteurs, accès accueil

Objets présents : 

#### Toilettes

Éléments présents : 1 porte, 1 interrupteur, 1 Lavabo, 1 chasse d'eau, 1 poubelle.

Objets présents : 1 savon

#### Salle de pause

Éléments présents : 1 porte, 1 interrupteur, 1 fenêtre, 1 table, 10 chaises, machine à café, 1 poubelle

Objets présents : 

#### Accueil

Éléments présents : 3 portes (Nord, Sud Est, Sud Ouest, Ouest), 1 tiroir, accès couloir, 1 fenêtre, 1 bureau, 3 chaises, 1 étagère, 1 poubelle, 1 ordinateur, 1 distributeur, 4 interrupteurs.

Objets présents : 

#### Ascenseur

Éléments présents : Digicode Badge, 1 porte (Nord)

Objets présents : 

#### Compta 

Éléments présents : 1 bureau, 2 tiroirs, 1 chaise, 1 fenêtre, 1 porte, 1 interrupteur, 1 étagère, 1 poubelle. 

Objets présents : 

#### Bureau Boss

Éléments présents : 1 bureau, 2 tiroirs, 1 chaise, 1 fenêtre, 1 porte, 1 interrupteur, 1 étagère, 1 poubelle.

Objets présents : 



### Éléments

définition : Ce avec quoi le protagoniste peut intéragir

#### Porte 

#### Contenant

Boite

Cartons

Tiroir

#### Digicode

#### Ordinateurs

Mdp pour intéragir avec le PC et l'IA (nom IA TODO) ou pas

#### Chasse d'eau

#### Fenêtre

#### Vasque 

Une minute de paralysie du bras s'il se lave les mains.

Lavabo

Évier

#### Étagère

#### Chaise

#### Table

#### Machine

Machine à café

Distributeur

Imprimante

#### Poubelle





### Objets

définition : Ce que le protagoniste peut prendre

#### Clé

#### Post-it

#### Badge

#### Savon 

#### Lame 

Ciseau 

Cutter

#### Document




## Analyse

## Cas d'utilisation

## Diagramme de classe

### Conception

## Architecture logique

## Implémentation

## Conception détaillée

### Manuel utilisateur

### Bilan